title = "Notre-Dame de Paris"
baseURL = "https://gohugo-theme-ananke.pages.dev"
languageCode = "en-us"
theme = "gohugo-theme-ananke"
resourceDir = "../resources"

[languages]
  [languages.en]
    title = "Rui Zhu"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = "/images/favicon.ico"
  description = "University of New South Wales (UNSW)"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/J17NotFound"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
